/*
===============================================================================
DDL Script: Create Silver Tables (PostgreSQL)
===============================================================================
Script Purpose:
    This script creates the 'silver.loan_data' table, dropping it if it exists.
    The Silver layer involves data type casting from the Bronze layer.
===============================================================================
*/

DROP TABLE IF EXISTS silver.loan_data;

CREATE TABLE silver.loan_data (
    loan_id                         INT,
    loan_amnt                       NUMERIC, 
    funded_amnt                     NUMERIC, 
    funded_amnt_inv                 NUMERIC, 
    term                            VARCHAR(50), 
    int_rate                        VARCHAR(20), 
    installment                     NUMERIC, 
    grade                           VARCHAR(10), 
    sub_grade                       VARCHAR(10),
    emp_length                      VARCHAR(50), 
    home_ownership                  VARCHAR(50), 
    annual_inc                      NUMERIC,
    issue_d                         VARCHAR(20), 
    loan_status                     VARCHAR(50),
    purpose                         VARCHAR(100),
    addr_state                      VARCHAR(10), 
    dti                             NUMERIC, 
    delinq_2yrs                     INT, 
    earliest_cr_line                VARCHAR(20), 
    fico_range_low                  INT, 
    fico_range_high                 INT, 
    inq_last_6mths                  INT, 
    mths_since_last_delinq          INT,
    open_acc                        INT, 
    pub_rec                         INT, 
    revol_bal                       NUMERIC, 
    revol_util                      VARCHAR(20), 
    total_acc                       INT,
    out_prncp                       NUMERIC, 
    out_prncp_inv                   NUMERIC, 
    total_pymnt                     NUMERIC,
    total_rec_prncp                 NUMERIC, 
    total_rec_int                   NUMERIC, 
    total_rec_late_fee              NUMERIC, 
    recoveries                      NUMERIC, 
    collection_recovery_fee         NUMERIC, 
    last_pymnt_d                    VARCHAR(20), 
    last_pymnt_amnt                 NUMERIC,
    last_credit_pull_d              VARCHAR(20), 
    last_fico_range_high            INT, 
    last_fico_range_low             INT, 
    collections_12_mths_ex_med      INT, 
    mths_since_last_major_derog     INT,
    acc_now_delinq                  INT, 
    tot_coll_amt                    NUMERIC, 
    tot_cur_bal                     NUMERIC,
    total_rev_hi_lim                NUMERIC,
    acc_open_past_24mths            INT, 
    avg_cur_bal                     NUMERIC, 
    bc_open_to_buy                  NUMERIC, 
    bc_util                         NUMERIC, 
    chargeoff_within_12_mths        INT, 
    delinq_amnt                     NUMERIC, 
    mo_sin_old_il_acct              INT, 
    mo_sin_old_rev_tl_op            INT, 
    mo_sin_rcnt_rev_tl_op           INT, 
    mo_sin_rcnt_tl                  INT, 
    mort_acc                        INT, 
    mths_since_recent_bc            INT, 
    mths_since_recent_bc_dlq        INT, 
    mths_since_recent_inq           INT, 
    mths_since_recent_revol_delinq  INT, 
    num_accts_ever_120_pd           INT, 
    num_actv_bc_tl                  INT, 
    num_actv_rev_tl                 INT, 
    num_bc_sats                     INT, 
    num_bc_tl                       INT, 
    num_il_tl                       INT, 
    num_op_rev_tl                   INT, 
    num_rev_accts                   INT, 
    num_rev_tl_bal_gt_0             INT, 
    num_sats                        INT, 
    num_tl_120dpd_2m                INT, 
    num_tl_30dpd                    INT, 
    num_tl_90g_dpd_24m              INT, 
    num_tl_op_past_12m              INT, 
    pct_tl_nvr_dlq                  NUMERIC, 
    percent_bc_gt_75                NUMERIC, 
    pub_rec_bankruptcies            INT, 
    tax_liens                       INT, 
    tot_hi_cred_lim                 NUMERIC, 
    total_bal_ex_mort               NUMERIC, 
    total_bc_limit                  NUMERIC, 
    total_il_high_credit_limit      NUMERIC,
    disbursement_method             VARCHAR(50), 
    debt_settlement_flag            VARCHAR(10), 
    debt_settlement_flag_date       VARCHAR(20), 
    settlement_status               VARCHAR(50), 
    settlement_date                 VARCHAR(20), 
    settlement_amount               NUMERIC, 
    settlement_percentage           NUMERIC, 
    settlement_term                 INT,
    dwh_create_date                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);